// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw06tDra21XQ137B0IR7khl-d3U584IOQ',
    appId: '1:1059054482858:web:dc4c92036aa6b43ac727d3',
    messagingSenderId: '1059054482858',
    projectId: 'mydemoapptest-16fc0',
    authDomain: 'mydemoapptest-16fc0.firebaseapp.com',
    storageBucket: 'mydemoapptest-16fc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDECAjilaGWOLu-pmQH4_y1vYfyrdZT09M',
    appId: '1:1059054482858:android:c8164eba3f3657b4c727d3',
    messagingSenderId: '1059054482858',
    projectId: 'mydemoapptest-16fc0',
    storageBucket: 'mydemoapptest-16fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXy3zfgUOVUQuIN3PchTEC_xGAvTzmVp0',
    appId: '1:1059054482858:ios:bb9cd35c9f9616ecc727d3',
    messagingSenderId: '1059054482858',
    projectId: 'mydemoapptest-16fc0',
    storageBucket: 'mydemoapptest-16fc0.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXy3zfgUOVUQuIN3PchTEC_xGAvTzmVp0',
    appId: '1:1059054482858:ios:cadf93ce4c9c3332c727d3',
    messagingSenderId: '1059054482858',
    projectId: 'mydemoapptest-16fc0',
    storageBucket: 'mydemoapptest-16fc0.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
